routes/web.php
Route::get('/project-service/get-projects-subcustomer', 'ProjectServiceController@get_projects_for_sub_customer')->name('get-projects-sub');
Route::post('/project-service/get-projects', 'ProjectServiceController@get_projects_for_branch')->name('get-projects');
Route::post('/project-service/get-customers', 'ProjectServiceController@get_customers_for_project')->name('get-customers');
Route::post('/project-service/get-sub-customers', 'ProjectServiceController@get_sub_customers')->name('get-sub-customers');
Route::post('/project-service/create', 'ProjectServiceController@store')->name('store-project-service');
Route::get('/project_service/{id}', 'ProjectServiceController@index');
Route::post('/project-service/duplicate', 'ProjectServiceController@duplicate')->name('duplicate-project-service');
Route::post('/project_service/add_person_to_project_service', 'ProjectServiceController@add_person')->name('add_person_to_project_service');
Route::post('/project_service/edit_project_service_person', 'ProjectServiceController@edit_person')->name('edit_project_service_person');
Route::delete('/project_service/delete_person_from_project_service', 'ProjectServiceController@delete_person')->name('delete_person_from_project_service');

Route::post('/project_service/delete_note_from_project_service', 'ProjectServiceController@delete_note')->name('delete_note_from_project_service');

Route::post('/project_service/ajax_get_address', 'ProjectServiceController@ajax_get_address')->name('ajax_get_address');
Route::post('/project_service/add_address_to_project_service', 'ProjectServiceController@add_address')->name('add_address_to_project_service');
Route::post('/project_service/edit_address_project_service', 'ProjectServiceController@edit_address')->name('edit_address_project_service');
Route::delete('/project_service/delete_address_from_project_service', 'ProjectServiceController@delete_address')->name('delete_address_from_project_service');
Route::post('/project_service/add_equipment_to_project_service', 'ProjectServiceController@add_equipment')->name('add_equipment_to_project_service');
Route::post('/project_service/edit_equipment_ps', 'ProjectServiceController@edit_equipment_ps')->name('edit_equipment_ps');
Route::delete('/project_service/delete_equipment_from_project_service', 'ProjectServiceController@delete_equipment')->name('delete_equipment_from_project_service');
Route::post('/project_service/add_supplies_to_project_service', 'ProjectServiceController@add_supplies')->name('add_supplies_to_project_service');
Route::post('/project_service/edit_supplies_project_service', 'ProjectServiceController@edit_supplies_ps')->name('edit_supplies_ps');
Route::post('/project_service/add_note_to_project_service', 'ProjectServiceController@add_note')->name('add_note_to_project_service')->middleware(['XSS']);
Route::post('/project_service/upload_project_service_document', 'ProjectServiceController@add_document')->name('upload_project_service_document');
Route::delete('/project_service/delete_supplies_from_project_service', 'ProjectServiceController@delete_supplies')->name('delete_supplies_from_project_service');
Route::get('project_service/{id}/edit', 'ProjectServiceController@edit')->name('edit-project-service');
Route::put('/project_service/{id}', 'ProjectServiceController@update')->name('update-project-service');
Route::post('file/upload', 'ProjectServiceController@uploadFile')->name('file.upload');
Route::delete('file/delete_file_ps', 'ProjectServiceController@delete_file_ps')->name('delete_file_ps');
Route::post('/project_service/ajax_status', 'ProjectServiceController@ajax_update_status')->name('ajax_update_status');
Route::post('/project_service/ajax_send_payroll_api', 'ProjectServiceController@ajax_send_payroll_api')->name('ajax_send_payroll_api');
Route::post('/project_service/ajax_delete_payroll_api', 'ProjectServiceController@ajax_delete_payroll_api')->name('ajax_delete_payroll_api');
Route::post('/project_service/ajax_update_payroll_api', 'ProjectServiceController@ajax_update_payroll_api')->name('ajax_update_payroll_api');
Route::post('/project_service/ajax_update_nickname', 'ProjectServiceController@ajax_update_nickname')->name('ajax_update_nickname');
Route::post('/project_service/{id}/ajax_edit_ps_project', 'ProjectServiceController@ajax_edit_ps_project');
Route::post('/project_service/ajax_add_new_address', 'ProjectServiceController@ajax_add_new_address')->name('ajax_add_new_address');
Route::post('/project_service/ajax_add_new_contact', 'ProjectServiceController@ajax_add_new_contact')->name('ajax_add_new_contact');
//Projects
Route::get('/projects', 'ProjectController@index')->name('projects');
Route::get('/projects/create', 'ProjectController@create')->name('create-project');
Route::get('/projects/{id}/edit', 'ProjectController@edit')->name('edit-project');
Route::get('/projects/{id}', 'ProjectController@show');
Route::put('/projects/{id}', 'ProjectController@update')->name('update-project');
Route::post('/projects', 'ProjectController@store')->name('store-project');
Route::post('/projects/get-booked-by', 'PersonController@get_booked_by')->name('get-booked-by');
Route::post('/projects/get-managed-by', 'PersonController@get_managed_by')->name('get-managed-by');

//People
Route::resource('people', 'PersonController');
Route::get('/people/create', 'PersonController@create')->name('create-person');
Route::post('/people', 'PersonController@store')->name('store-person');
Route::post('/project_service/add_person_ajax', 'PersonController@add_person_ajax')->name('store-person-ajax');
// Route::get('/people/{id}/edit', 'PersonController@edit')->name('edit-person');
// Route::post('/people/{id}/update', 'PersonController@update')->name('update-person');
Route::get('person_autocomplete',array('as'=>'person_autocomplete','uses'=>'PersonController@person_autocomplete'));
Route::get('employee_autocomplete',array('as'=>'employee_autocomplete','uses'=>'PersonController@employee_autocomplete'));

//Companies
Route::resource('companies', 'CompanyController');
Route::get('customer_autocomplete',array('as'=>'customer_autocomplete','uses'=>'CompanyController@customer_autocomplete'));
//Addresses
Route::get('address_autocomplete',array('as'=>'address_autocomplete','uses'=>'AddressController@address_autocomplete'));

// Equipment
Route::resource('addresses', 'AddressController');
Route::resource('equipment', 'EquipmentController');
// Supplies
Route::resource('supplies', 'SuppliesController');
// Service Roles
Route::resource('service_role', 'ServiceRoleController');

//Reports
Route::get('/reports', 'ReportController@index')->name('reports');
Route::post('/reports/supervisor_control', 'ReportController@supervisor_control')->name('supervisor-control');
Route::post('/reports/time_sheet', 'ReportController@time_sheet')->name('time-sheet');
Route::post('/reports/work_order', 'ReportController@work_order')->name('work-order');
Route::post('/reports/summary_dispatch', 'ReportController@summary_dispatch')->name('summary-dispatch');

// Import data routes
if (App::environment('development'))
{
  Route::get('/data', 'DataController@index')->name('data');
  Route::post('/data/import_companies', 'DataController@import_companies')->name('import_companies');
  Route::post('/data/create_company_types', 'DataController@create_company_types')->name('create_company_types');
  Route::post('/data/import_cities', 'DataController@import_cities')->name('import_cities');
  Route::post('/data/import_countries', 'DataController@import_countries')->name('import_countries');
  Route::post('/data/import_provinces', 'DataController@import_provinces')->name('import_provinces');
  Route::post('/data/import_addresses', 'DataController@import_addresses')->name('import_addresses');
  Route::post('/data/import_people', 'DataController@import_people')->name('import_people');
  Route::post('/data/import_company_people', 'DataController@import_company_people')->name('import_company_people');
  Route::post('/data/import_projects_table', 'DataController@import_projects_table')->name('import_projects_table');
  Route::post('/data/import_projectservices_table', 'DataController@import_projectservices_table')->name('import_projectservices_table');
  Route::post('/data/import_services_table', 'DataController@import_services_table')->name('import_services_table');
  Route::post('/data/import_project_services_notes', 'DataController@import_project_service_notes')->name('import_project_service_notes');
  Route::post('/data/import_project_service_files', 'DataController@import_project_services_files')->name('import_project_services_files');
  Route::post('/data/import_project_services_people', 'DataController@import_project_services_people')->name('import_project_services_people');
  Route::post('/data/import_service_roles', 'DataController@import_service_roles')->name('import_service_roles');
  Route::post('/data/import_project_services_addresses', 'DataController@import_project_services_addresses')->name('import_project_services_addresses');
  Route::post('/data/import_company_addresses', 'DataController@import_company_addresses')->name('import_company_addresses');
  Route::post('/data/import_street_type', 'DataController@import_street_type')->name('import_street_type');
  Route::post('/data/import_project_services_equipment', 'DataController@import_project_services_equipment')->name('import_project_services_equipment');
  Route::post('/data/import_equipment', 'DataController@import_equipment')->name('import_equipment');
  Route::post('/data/import_supplies', 'DataController@import_supplies')->name('import_supplies');
  Route::post('/data/import_project_service_supplies', 'DataController@import_project_service_supplies')->name('import_project_service_supplies');
  Route::post('/data/import_users', 'DataController@import_users')->name('import_users');
  Route::post('/data/compile_addresses', 'DataController@compile_addresses')->name('compile_addresses');

app/Company.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Company extends Model
{
    use SoftDeletes;


    public function type() {
        return $this->hasOne('App\CompanyType', 'id','type_id');
    }

    public function project() {
        return $this->hasMany('App\Project', 'customer_id');
    }
    
    public function apis() {
        return $this->hasMany('App\ApiLocation', 'location_id');
    }

}

app/CompanyType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CompanyType extends Model
{ 
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Company;
use App\Project;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::orderBy('name')
        ->paginate(50);


        return view('companies.index', ['companies'=>$companies]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $company = New Company;
        $company->old_id = 0;
        $company->name = $request->name;
        $company->type_id = $request->type_id;
        $company->email = $request->email;
        $company->url = $request->url;
        $company->phone = $request->phone;
        $company->fax = '';
        $company->parent_company_id = $request->parent_company;
        $company->note = $request->note;
        $company->save();
        return $this->show($company->id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::where('id', '=', $id)
        ->first();
        $parent = [];
        $parent = Company::where('id', '=', $company->parent_company_id)->first();
        return view('companies.edit', ['company'=>$company, 'parent'=> $parent]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $company = Company::where('id', '=', $id)
        ->first();
        $parent = [];
        $parent = Company::where('id', '=', $company->parent_company_id)->first();
        $projects = [];
        $projects = Project::where('customer_id', '=', $company->id)->get();
  
        return view('companies.show', ['company'=>$company, 'parent'=> $parent, 'projects'=>$projects]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        // dd($request->all());
        $company = Company::where('id', '=', $id)
        ->first();
        $company->old_id = 0;
        $company->name = $request->name;
        $company->type_id = $request->type_id;
        $company->email = $request->email;
        $company->url = $request->url;
        $company->phone = $request->phone;
        $company->fax = '';
        $company->parent_company_id = $request->parent_company;
        $company->note = $request->note;
        
        $company->save();
        return $this->show($company->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
    
  public function customer_autocomplete(Request $request) {
    $data = Company::select('id', 'name')->where("name","LIKE","%{$request->input('query')}%")->get();
    return response()->json($data);
  }
}

resources/views/companies/create.blade.php
@extends('layouts.app')

@section('content')

<div class="text-gray-900 mt-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div>
    <h2 class="mt-4 mb-2 h1 text-center">Add New Company</h2>
    <form class="mt-4" id="create-company-form" action="{{route('companies.store')}}" method="POST">
      @csrf 
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" type="text" name="name" id="name" required />
      </div>
      <div class="form-group">
        <label for="type_id">Company Type</label>
        <select class="form-control" type="text" name="type_id" id="type_id">
          <option value="1">Customer</option>
          <option value="2">Branch</option>
        </select>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input class="form-control" type="email" name="email" id="email" />
      </div>
      <div class="form-group">
        <label for="url">Website</label>
        <input class="form-control" type="text" name="url" id="url" />
      </div>
      <div class="form-group">
        <label for="phone">Phone</label>
        <input class="form-control" type="text" name="phone" id="phone" />
      </div>
      <div class="form-group">
        <label for="parent_company">Parent Company</label>
        <input class="form-control" type="text" name="parent_company_name" id="parent_company" />
        <input type="hidden" name="parent_company" id="parent-company-id"/>
      </div>
      <div class="form-group">
        <label for="note">Notes</label>
        <textarea class="form-control" type="text" name="note" id="note"></textarea>
      </div>
      <div class="form-group">
        <input type="submit" class="btn btn-primary" id="create-service">
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
  
let path = "{{ route('customer_autocomplete') }}";
  $('#parent_company').typeahead({
        items: 50,
      source:  function (query, process) {
          return $.get(path, { query: query }, function (data) {
              return process(data);
          });
      },
      highlighter: function (item, data) {
          var parts = item.split('#'),
              html = '<div class="row">';
              html += '<div class="col-md-2">';
              html += '</div>';
              html += '<div class="col-md-10 pl-0">';
              html += '<span>'+data.name+'</span>';
              html += '</div>';
              html += '</div>';

          return html;
      },
      afterSelect:function(data,value,text){
          $('#parent-company-id').val(data.id)
      },
  })
</script>
@endpush

resources/views/companies/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="text-gray-900 mt-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div>
    <h2 class="mt-4 mb-2 h1 text-center">Edit Company</h2>
    <form class="mt-4" id="update-company-form" action="{{route('companies.update', $company->id)}}" method="POST">
      @csrf 
      @method('PUT')
      <div class="form-group">
        <label for="name">Name</label>
        <input class="form-control" type="text" name="name" id="name" value="{{$company->name}}" required />
      </div>
      <div class="form-group">
        <label for="type_id">Company Type</label>
        <select class="form-control" type="text" name="type_id" id="type_id">
          <option value="1" @if($company->type_id == 1)selected @endif>Customer</option>
          <option value="2" @if($company->type_id == 2)selected @endif>Branch</option>
        </select>
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input class="form-control" type="email" name="email" id="email" required value="{{$company->email}}" />
      </div>
      <div class="form-group">
        <label for="url">Website</label>
        <input class="form-control" type="text" name="url" id="url" value="{{$company->url}}" />
      </div>
      <div class="form-group">
        <label for="phone">Phone</label>
        <input class="form-control" type="text" name="phone" id="phone" required value="{{$company->phone}}" />
      </div>
      <div class="form-group">
        <label for="parent_company">Parent Company</label>
        <input class="form-control" type="text" name="parent_company_name" id="parent_company" 
        value="{{ $parent->name ?? ''}}" />
        <input type="hidden" name="parent_company" id="parent-company-id" value="{{ $parent->id ?? ''}}"/>
      </div>
      <div class="form-group">
        <label for="note">Notes</label>
        <textarea class="form-control" type="text" name="note" id="note">{{$company->note}}</textarea>
      </div>
      <div class="form-group">
        <input type="submit" class="btn btn-primary" id="create-company">
        <a href="/companies/{{$company->id}}" class="btn btn-danger ml-3">Cancel</a>
      </div>
    </form>
  </div>
</div>
@endsection

@push('scripts')
<script>
  
let path = "{{ route('customer_autocomplete') }}";
  $('#parent_company').typeahead({
        items: 50,
      source:  function (query, process) {
          return $.get(path, { query: query }, function (data) {
              return process(data);
          });
      },
      highlighter: function (item, data) {
          var parts = item.split('#'),
              html = '<div class="row">';
              html += '<div class="col-md-2">';
              html += '</div>';
              html += '<div class="col-md-10 pl-0">';
              html += '<span>'+data.name+'</span>';
              html += '</div>';
              html += '</div>';

          return html;
      },
      afterSelect:function(data,value,text){
          $('#parent-company-id').val(data.id)
      },
  })
</script>
@endpush

resources/views/companies/index.blade.php
@extends('layouts.app')

@section('content')

<div class="text-gray-900 mt-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div>
    <h2 class="mt-4 mb-2 h1 font-weight-bold text-center">Companies</h2>
    {{-- @include('components/people-filter') --}}
    
    <div class="d-flex flex-column">
      <div class="my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full overflow-hidden sm:rounded-lg">
          <div class="border text-left p-4">
            <h3 class="h5 font-weight-normal">Find</h3>
            <input class="form-control" type="text" name="company" id="company" required />
            <div class="d-flex justify-content-end mt-2">
              <a href="/companies/create" class="btn btn-sm btn-info">Add Company</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <table class="table table-sm table-striped table-hover mt-4">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Email
          </th>
          <th>
            Phone
          </th>
          <th>

          </th>
        </tr>
      </thead>
      <tbody>
        @foreach($companies as $company)
        <tr>
          <td>
            {{ $company->name }}
          </td>
          <td>
            <a href="mailto:{{$company->email}}">
            {{ $company->email }}
            </a>
          </td>
          <td>
            <span><a href="tel:{{$company->phone}}"> {{$company->phone}}</a></span>
          </td>
          <td>
            <a href="/companies/{{$company->id}}" class="btn btn-sm btn-primary">View</a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-end my-4">
    @if ($companies->hasPages())
    {{ $companies->appends(Request::except('page'))->links() }}
    @endif
  </div>
</div>
@endsection

@push('scripts')
<script>
  let path = "{{ route('customer_autocomplete') }}";
  $('#company').typeahead({
      source:  function (query, process) {
          return $.get(path, { query: query }, function (data) {
              return process(data);
          });
      },
      highlighter: function (item, data) {
          var parts = item.split('#'),
              html = '<div class="row">';
              html += '<div class="col-md-2">';
              html += '</div>';
              html += '<div class="col-md-10 pl-0">';
              html += '<span>'+data.name+'</span>';
              html += '</div>';
              html += '</div>';

          return html;
      },
      afterSelect:function(data,value,text){
          window.location.href = "/companies/" + data.id
      },
  })
</script>
@endpush

resources/views/companies/show.blade.php
@extends('layouts.app')

@section('content')

<div class="text-gray-900 mt-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div>
    <h2 class="mt-4 mb-2 h1 font-weight-bold text-center">
      {{ $company->name }}
    </h2>
    <div class="d-flex flex-column">
      <div class="my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full overflow-hidden sm:rounded-lg">
          <div class="border text-left p-4">
            <div class="d-flex justify-content-between align-items-start">
            <table>
              <tr>
                <td>
                  <span class="font-weight-bold col">Name: </span>
                </td>
                <td>
                  <span>{{$company->name}} </span>
                </td>
              </tr>
              @if(isset($parent->name))
              <tr>
                <td>
                  <span class="font-weight-bold col">Parent Company: </span>
                </td>
                <td>
                  @if(isset($parent->name))
                  <span>{{$parent->name}} </span>
                  @endif
                </td>
              </tr>
              @endif
              <tr>
                <td>
                  <span class="font-weight-bold col">Phone: </span>
                </td>
                <td>
                  <span><a href="tel:{{$company->phone}}"> {{$company->phone}}</a></span>
                </td>
              </tr>
              <tr>
                <td>
                  <span class="font-weight-bold col">Email: </span>
                </td>
                <td>
                  <span><a href="mailto:{{$company->email}}"> {{$company->email}}</a></span>
                </td>
              </tr>
              <tr>
                <td>
                  <span class="font-weight-bold col">Website: </span>
                </td>
                <td>
                  <span><a href="{{$company->url}}" target="_blank"> {{$company->url}}</a></span>
                </td>
              </tr>
              <tr>
                <td>
                  <span class="font-weight-bold col">Notes: </span>
                </td>
                <td>
                  <span>{{$company->note}}</span>
                </td>
              </tr>
            </table>
            <div class="d-flex flex-column">
              <a href="{{route('create-project', ['customer_id' => $company->id])}}" class="btn btn-sm btn-info">Add Project</a>
              <a href="/companies/{{$company->id}}/edit" class="mt-2 btn btn-sm btn-info">Edit Company</a>
            </div>
          </div>
          </div>
        </div>
      </div>

      <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
        <div class="align-middle inline-block min-w-full overflow-hidden sm:rounded-lg">
          <div class="border mb-4 text-left p-4">
            <h2 class="mb-4 font-bold text-xl">Projects</h2>
            <ul>
              @foreach($projects as $project)
              <li>
                {{$project->id}} - {{$project->name}}- <a href="/projects/{{$project->id}}">View</a>
              </li>
              @endforeach
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection