routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Password;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', [
    'as' => 'login',
    'uses' => 'Auth\LoginController@showLoginForm'
  ]);

Route::post('/', [
  'as' => '',
  'uses' => 'Auth\LoginController@login'
]);

Route::get('/forgot-password', function () {
  return view('auth.forgot-password');
})->middleware('guest')->name('password.request');

Route::post('/forgot-password', function (Request $request) {
  $request->validate(['email' => 'required|email']);

  $status = Password::sendResetLink(
      $request->only('email')
  );

  return $status === Password::RESET_LINK_SENT
              ? back()->with(['status' => __($status)])
              : back()->withErrors(['email' => __($status)]);
})->middleware('guest')->name('password.email');

// Route::get('/{any}', 'SpaController@index')->where('any', '.*');
Route::get('/dashboard', 'HomeController@index')->name('dashboard');
// Route::post('/dashboard', 'HomeController@index')->name('dashboard');

//Project SErvices
Route::get('/project-service/create', 'ProjectServiceController@create')->name('create-service');
Route::get('/project-service/get-projects-subcustomer', 'ProjectServiceController@get_projects_for_sub_customer')->name('get-projects-sub');
Route::post('/project-service/get-projects', 'ProjectServiceController@get_projects_for_branch')->name('get-projects');
Route::post('/project-service/get-customers', 'ProjectServiceController@get_customers_for_project')->name('get-customers');
Route::post('/project-service/get-sub-customers', 'ProjectServiceController@get_sub_customers')->name('get-sub-customers');
Route::post('/project-service/create', 'ProjectServiceController@store')->name('store-project-service');
Route::get('/project_service/{id}', 'ProjectServiceController@index');
Route::post('/project-service/duplicate', 'ProjectServiceController@duplicate')->name('duplicate-project-service');
Route::post('/project_service/add_person_to_project_service', 'ProjectServiceController@add_person')->name('add_person_to_project_service');
Route::post('/project_service/edit_project_service_person', 'ProjectServiceController@edit_person')->name('edit_project_service_person');
Route::delete('/project_service/delete_person_from_project_service', 'ProjectServiceController@delete_person')->name('delete_person_from_project_service');

Route::post('/project_service/delete_note_from_project_service', 'ProjectServiceController@delete_note')->name('delete_note_from_project_service');

Route::post('/project_service/ajax_get_address', 'ProjectServiceController@ajax_get_address')->name('ajax_get_address');
Route::post('/project_service/add_address_to_project_service', 'ProjectServiceController@add_address')->name('add_address_to_project_service');
Route::post('/project_service/edit_address_project_service', 'ProjectServiceController@edit_address')->name('edit_address_project_service');
Route::delete('/project_service/delete_address_from_project_service', 'ProjectServiceController@delete_address')->name('delete_address_from_project_service');
Route::post('/project_service/add_equipment_to_project_service', 'ProjectServiceController@add_equipment')->name('add_equipment_to_project_service');
Route::post('/project_service/edit_equipment_ps', 'ProjectServiceController@edit_equipment_ps')->name('edit_equipment_ps');
Route::delete('/project_service/delete_equipment_from_project_service', 'ProjectServiceController@delete_equipment')->name('delete_equipment_from_project_service');
Route::post('/project_service/add_supplies_to_project_service', 'ProjectServiceController@add_supplies')->name('add_supplies_to_project_service');
Route::post('/project_service/edit_supplies_project_service', 'ProjectServiceController@edit_supplies_ps')->name('edit_supplies_ps');
Route::post('/project_service/add_note_to_project_service', 'ProjectServiceController@add_note')->name('add_note_to_project_service')->middleware(['XSS']);
Route::post('/project_service/upload_project_service_document', 'ProjectServiceController@add_document')->name('upload_project_service_document');
Route::delete('/project_service/delete_supplies_from_project_service', 'ProjectServiceController@delete_supplies')->name('delete_supplies_from_project_service');
Route::get('project_service/{id}/edit', 'ProjectServiceController@edit')->name('edit-project-service');
Route::put('/project_service/{id}', 'ProjectServiceController@update')->name('update-project-service');
Route::post('file/upload', 'ProjectServiceController@uploadFile')->name('file.upload');
Route::delete('file/delete_file_ps', 'ProjectServiceController@delete_file_ps')->name('delete_file_ps');
Route::post('/project_service/ajax_status', 'ProjectServiceController@ajax_update_status')->name('ajax_update_status');
Route::post('/project_service/ajax_send_payroll_api', 'ProjectServiceController@ajax_send_payroll_api')->name('ajax_send_payroll_api');
Route::post('/project_service/ajax_delete_payroll_api', 'ProjectServiceController@ajax_delete_payroll_api')->name('ajax_delete_payroll_api');
Route::post('/project_service/ajax_update_payroll_api', 'ProjectServiceController@ajax_update_payroll_api')->name('ajax_update_payroll_api');
Route::post('/project_service/ajax_update_nickname', 'ProjectServiceController@ajax_update_nickname')->name('ajax_update_nickname');
Route::post('/project_service/{id}/ajax_edit_ps_project', 'ProjectServiceController@ajax_edit_ps_project');
Route::post('/project_service/ajax_add_new_address', 'ProjectServiceController@ajax_add_new_address')->name('ajax_add_new_address');
Route::post('/project_service/ajax_add_new_contact', 'ProjectServiceController@ajax_add_new_contact')->name('ajax_add_new_contact');
//Projects
Route::get('/projects', 'ProjectController@index')->name('projects');
Route::get('/projects/create', 'ProjectController@create')->name('create-project');
Route::get('/projects/{id}/edit', 'ProjectController@edit')->name('edit-project');
Route::get('/projects/{id}', 'ProjectController@show');
Route::put('/projects/{id}', 'ProjectController@update')->name('update-project');
Route::post('/projects', 'ProjectController@store')->name('store-project');
Route::post('/projects/get-booked-by', 'PersonController@get_booked_by')->name('get-booked-by');
Route::post('/projects/get-managed-by', 'PersonController@get_managed_by')->name('get-managed-by');

//People
Route::resource('people', 'PersonController');
Route::get('/people/create', 'PersonController@create')->name('create-person');
Route::post('/people', 'PersonController@store')->name('store-person');
Route::post('/project_service/add_person_ajax', 'PersonController@add_person_ajax')->name('store-person-ajax');
// Route::get('/people/{id}/edit', 'PersonController@edit')->name('edit-person');
// Route::post('/people/{id}/update', 'PersonController@update')->name('update-person');
Route::get('person_autocomplete',array('as'=>'person_autocomplete','uses'=>'PersonController@person_autocomplete'));
Route::get('employee_autocomplete',array('as'=>'employee_autocomplete','uses'=>'PersonController@employee_autocomplete'));

//Companies
Route::resource('companies', 'CompanyController');
Route::get('customer_autocomplete',array('as'=>'customer_autocomplete','uses'=>'CompanyController@customer_autocomplete'));
//Addresses
Route::get('address_autocomplete',array('as'=>'address_autocomplete','uses'=>'AddressController@address_autocomplete'));

// Equipment
Route::resource('addresses', 'AddressController');
Route::resource('equipment', 'EquipmentController');
// Supplies
Route::resource('supplies', 'SuppliesController');
// Service Roles
Route::resource('service_role', 'ServiceRoleController');

//Reports
Route::get('/reports', 'ReportController@index')->name('reports');
Route::post('/reports/supervisor_control', 'ReportController@supervisor_control')->name('supervisor-control');
Route::post('/reports/time_sheet', 'ReportController@time_sheet')->name('time-sheet');
Route::post('/reports/work_order', 'ReportController@work_order')->name('work-order');
Route::post('/reports/summary_dispatch', 'ReportController@summary_dispatch')->name('summary-dispatch');

// Import data routes
if (App::environment('development'))
{
  Route::get('/data', 'DataController@index')->name('data');
  Route::post('/data/import_companies', 'DataController@import_companies')->name('import_companies');
  Route::post('/data/create_company_types', 'DataController@create_company_types')->name('create_company_types');
  Route::post('/data/import_cities', 'DataController@import_cities')->name('import_cities');
  Route::post('/data/import_countries', 'DataController@import_countries')->name('import_countries');
  Route::post('/data/import_provinces', 'DataController@import_provinces')->name('import_provinces');
  Route::post('/data/import_addresses', 'DataController@import_addresses')->name('import_addresses');
  Route::post('/data/import_people', 'DataController@import_people')->name('import_people');
  Route::post('/data/import_company_people', 'DataController@import_company_people')->name('import_company_people');
  Route::post('/data/import_projects_table', 'DataController@import_projects_table')->name('import_projects_table');
  Route::post('/data/import_projectservices_table', 'DataController@import_projectservices_table')->name('import_projectservices_table');
  Route::post('/data/import_services_table', 'DataController@import_services_table')->name('import_services_table');

app/Person.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Company;

class Person extends Model
{
    protected $table = 'persons';

    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
    
    public function full_name() {
        return $this->first_name . " " . $this->last_name;
    }
    public function company_person () {
        return $this->hasOne('App\CompanyPerson', 'person_id', 'id');
    }

    public function user() {
        $this->hasOne('App\User', 'person_id', 'id');
    }
}

resources/views/people/create.blade.php
@extends('layouts.app')

@section('content')
<div class="text-gray-900 mt-5 mb-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <h2 class="text-center my-8 text-3xl font-extrabold">Add New Person</h2>
  <form class="mt-4 w-100" id="create-person-form" method="POST" action="{{route('store-person')}}">
    <div class="row">
      @csrf
      <div class="col-lg-6">
        <div class="form-group">
          <label for="title">Title</label>
          <select id="title" name="title" type='text' class="form-control">
            <option value="">Select Title</option>
            <option value="Mr.">Mr.</option>
            <option value="Mrs.">Mrs.</option>
            <option value="Ms.">Ms.</option>
            <option value="Miss">Miss</option>
          </select>
        </div>
        <div class="form-group">
          <label for="first_name">First Name <span>*</span></label>
          <input type="text" name="first_name" id="first_name" class="form-control" required />
        </div>
        <div class="form-group">
          <label for="middle_name">Middle Name</label>
          <input type="text" name="middle_name" id="middle_name" class="form-control" />
        </div>
        <div class="form-group">
          <label for="last_name">Last Name<span>*</span></label>
          <input type="text" name="last_name" id="last_name" class="form-control" required />
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" name="email" id="email" class="form-control" />
        </div>
        <div class="form-group">
          <label for="phone">Phone Primary *</label>
          <input type="text" name="phone" id="phone" class="form-control" required/>
        </div>
        <div class="form-group">
          <label for="mobile_phone">Phone Secondary</label>
          <input type="text" name="mobile_phone" id="mobile_phone" class="form-control" />
        </div>
        <div class="form-group">
          <label for="emergency">Emergency Contact</label>
          <input class="form-control" type="text" name="emerg_contact" id="emergency" />
        </div>
        <div class="form-group">
          <label for="notes">Notes</label>
          <textarea name="notes" id="notes" class="form-control"></textarea>
        </div>
        <div class="form-group">
          <label for="company">Company</label>
          <input class="typeahead form-control" type="text" name="company" id="company" />
          <input type="hidden" id="company-id" name="company_id" />
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-12">
        <input type="submit" class="btn btn-md btn-primary" value="Submit">
      </div>
      <div class="col-lg-12">
        <p class="small mt-">* denotes required field</p>
      </div>
    </div>
</form>
</div>

@endsection

@push('scripts')
<script>
  $(document).ready(function() {
    $('.datepicker').datetimepicker({
      timepicker: false
      , format: 'Y-m-d'
    });
  });

</script>

@endpush

resources/views/people/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="text-gray-900 mt-5 mb-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <h2 class="text-center my-8 text-3xl font-extrabold">Edit {{$person->person->first_name}} {{$person->person->last_name}}</h2>
  <form class="mt-4 w-100" id="create-person-form" method="POST" action="{{route('people.update', $person->id)}}">
  <div class="row">
      @csrf
      @method('PUT')
      <div class="col-lg-6">
        <div class="form-group">
          <label for="title">Title</label>
          <select id="title" name="title" type='text' class="form-control">
            <option value="">Select Title</option>
            <option value="Mr.">Mr.</option>
            <option value="Mrs.">Mrs.</option>
            <option value="Ms.">Ms.</option>
            <option value="Miss">Miss</option>
          </select>
        </div>
        <div class="form-group">
          <label for="first_name">First Name <span>*</span></label>
          <input type="text" name="first_name" id="first_name" class="form-control" value="{{$person->person->first_name}}" required />
        </div>
        <div class="form-group">
          <label for="middle_name">Middle Name</label>
          <input type="text" name="middle_name" id="middle_name" class="form-control" value="{{$person->person->middle_name}}" />
        </div>
        <div class="form-group">
          <label for="last_name">Last Name<span>*</span></label>
          <input type="text" name="last_name" id="last_name" class="form-control" value="{{$person->person->last_name}}" required />
        </div>
        <div class="form-group">
          <label for="email">Email</label>
          <input type="email" name="email" id="email" class="form-control" value="{{$person->person->email}}" />
        </div>
        <div class="form-group">
          <label for="phone">Phone</label>
          <input type="text" name="phone" id="phone" class="form-control" value="{{$person->person->phone}}" />
        </div>
        <div class="form-group">
          <label for="mobile_phone">Mobile Phone</label>
          <input type="text" name="mobile_phone" id="mobile_phone" class="form-control" value="{{$person->person->mobile_phone}}" />
        </div>
        <div class="form-group">
          <label for="emergency">Emergency Contact</label>
          <input class="form-control" type="text" name="emerg_contact" id="emergency" value="{{$person->emerg_contact ?? ''}}"s/>
        </div>
        <div class="form-group">
          <label for="notes">Notes</label>
          <textarea name="notes" id="notes" class="form-control">{{$person->person->notes}}</textarea>
        </div>
        
        <div class="form-group">
          <label for="company">Company</label>
          <input class="typeahead form-control" type="text" name="company" id="company" value="{{$person->company->name ?? ''}}" />
          <input type="hidden" id="company-id" name="company_id" value="{{$person->company->id ?? null}}" />
        </div>
      </div>

    <div class="col-lg-12">
      <input type="submit" class="btn btn-md btn-primary" value="Submit">
      <a href="/people/{{$person->id}}" class="btn btn-md btn-grey">Cancel</a>
    </div>
    <div class="col-lg-12">
      <p class="small mt-">* denotes required field</p>
    </div>
  </div>
</form>
</div>

@endsection

@push('scripts')
<script>
  $(document).ready(function() {
    $('.datepicker').datetimepicker({
      timepicker: false,
      format:'Y-m-d'
    });
  });

let path = "{{ route('customer_autocomplete') }}";
  $('#company').typeahead({
        items: 50,
      source:  function (query, process) {
          return $.get(path, { query: query }, function (data) {
              return process(data);
          });
      },
      items: 15,
      minLength: 3,
      highlighter: function (item, data) {
          var parts = item.split('#'),
              html = '<div class="row">';
              html += '<div class="col-md-2">';
              html += '</div>';
              html += '<div class="col-md-10 pl-0">';
              html += '<span>'+data.name+'</span>';
              html += '</div>';
              html += '</div>';

          return html;
      },
      afterSelect:function(data,value,text){
          $('#company-id').val(data.id)
      },
  })

let path2 = "{{ route('person_autocomplete') }}";
$('#emergency').typeahead({
        items: 50,
      source:  function (query, process) {
          return $.get(path2, { query: query }, function (data) {
              return process(data);
          });
      },
      items: 15,
      minLength: 3,
      highlighter: function (item, data) {
          var parts = item.split('#'),
              html = '<div class="row">';
              html += '<div class="col-md-2">';
              html += '</div>';
              html += '<div class="col-md-10 pl-0">';
              html += '<span>'+data.name+ '</span>';
              html += '</div>';
              html += '</div>';

          return html;
      },
      afterSelect:function(data,value,text){
          $('#emergency_contact_id').val(data.id)
      },
  })  
  $('#reports_to').typeahead({
        items: 50,
      source:  function (query, process) {
          return $.get(path2, { query: query }, function (data) {
              return process(data);
          });
      },
      items: 15,
      minLength: 3,
      highlighter: function (item, data) {
          var parts = item.split('#'),
              html = '<div class="row">';
              html += '<div class="col-md-2">';
              html += '</div>';
              html += '<div class="col-md-10 pl-0">';
              html += '<span>'+data.name+ '</span>';
              html += '</div>';
              html += '</div>';

          return html;
      },
      afterSelect:function(data,value,text){
          $('#reports_to_id').val(data.id)
      },
  })
</script>

@endpush

resources/views/people/index.blade.php
@extends('layouts.app')

@section('content')

<div class="text-gray-900 mt-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div>
    <h2 class="mt-4 mb-2 h1 font-weight-bold text-center">People</h2>
    @include('components/people-filter')
    <table class="table table-sm table-striped table-hover mt-4">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Company
          </th>
          <th>
            Email
          </th>
          <th>
            Phone
          </th>
          <th>

          </th>
        </tr>
      </thead>
      <tbody>
        @foreach($people as $individual)
        <tr>
          <td>
            {{ $individual->person->first_name }} {{ $individual->person->last_name }}
          </td>
          <td>
            {{ $individual->company->name }}
          </td>
          <td>
            <a href="mailto:{{$individual->email}}">
            {{ $individual->email }}
            </a>
          </td>
          <td>
            <a href="tel:{{$individual->phone}}">
              {{ $individual->phone }}
            </a>
          </td>
          <td>
            <a href="/people/{{$individual->id}}" class="btn btn-sm btn-primary">View</a>
            <a href="/people/{{$individual->id}}/edit" class="btn btn-sm btn-info ml-3">Edit</a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
  <div class="d-flex justify-end my-4">
    @if ($people->hasPages())
    {{ $people->appends(Request::except('page'))->links() }}
    @endif
  </div>
</div>
@endsection

resources/views/people/show.blade.php
@extends('layouts.app')

@section('content')

<div class="text-gray-900 mt-5">
  @if (session('status'))
  <div class="alert alert-success" role="alert">
    {{ session('status') }}
  </div>
  @endif
  <div>
    <div class="d-flex justify-content-between align-items-start">
      <h2 class="my-4 mb-2 h1 font-weight-bold text-center">
        {{ $person->person->first_name }} {{ $person->person->middle_name }} {{ $person->person->last_name }}
      </h2>
      <p class="m-0 text-right">
        <a href="/people">Back to People</a><br>
        <a class="btn btn-info mr-0" href="/people/{{$person->id}}/edit">Edit</a>
      </p>
    </div>
    <div class="mt-5">
      <table class="table table-sm">
        <tr>
          <td>
            <strong>Name: </strong>
          </td>
          <td>
            {{$person->person->first_name}} {{$person->person->middle_name}} {{$person->person->last_name}}
          </td>
        </tr>
        <tr>
          <td>
            <strong>email: </strong>
          </td>
          <td>
            <a href="mailto:{{$person->person->email}}">{{$person->person->email}}</a>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Phone: </strong>
          </td>
          <td>
            <a href="tel:{{$person->person->phone}}">{{$person->person->phone}}</a>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Mobile Phone: </strong>
          </td>
          <td>
            <a href="tel:{{$person->person->mobile_phone}}">{{$person->person->mobile_phone}}</a>
          </td>
        </tr>
        <tr>
          <td>
            <strong>Company: </strong>
          </td>
          <td>
            {{$person->company->name ?? ''}}
          </td>
        </tr>
        <tr>
          <td>
            <strong>Emergency Contact: </strong>
          </td>
          <td>
            {{$person->emerg_contact ?? ''}}
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
@endsection